### ISSUE TITLE
Android compilation failed after upgrade to 1.3.1

### ISSUE THREAD

**Issue by diego-paired** [SudoPlz/sp-react-native-in-app-updates#124]
Upgrading from 1.2.0 to 1.3.1, with React Native 0.70.6
Android compilation fails with the following error:

```
* What went wrong:
Execution failed for task ':app:checkDebugDuplicateClasses'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.CheckDuplicatesRunnable
   > Duplicate class com.google.android.play.core.appupdate.AppUpdateInfo found in modules jetified-app-update-2.0.1-runtime (com.google.android.play:app-update:2.0.1) and jetified-core-1.9.0-runtime (com.google.android.play:core:1.9.0)
     Duplicate class com.google.android.play.core.appupdate.AppUpdateManager found in modules jetified-app-update-2.0.1-runtime (com.google.android.play:app-update:2.0.1) and jetified-core-1.9.0-runtime (com.google.android.play:core:1.9.0)
     Duplicate class com.google.android.play.core.appupdate.AppUpdateManagerFactory found in modules jetified-app-update-2.0.1-runtime (com.google.android.play:app-update:2.0.1) and jetified-core-1.9.0-runtime (com.google.android.play:core:1.9.0)
     Duplicate class com.google.android.play.core.appupdate.AppUpdateOptions found in modules jetified-app-update-2.0.1-runtime (com.google.android.play:app-update:2.0.1) and jetified-core-1.9.0-runtime (com.google.android.play:core:1.9.0)
     Duplicate class com.google.android.play.core.appupdate.AppUpdateOptions$Builder found in modules jetified-app-update-2.0.1-runtime (com.google.android.play:app-update:2.0.1) and jetified-core-1.9.0-runtime (com.google.android.play:core:1.9.0)
     Duplicate class com.google.android.play.core.appupdate.testing.FakeAppUpdateManager found in modules jetified-app-update-2.0.1-runtime (com.google.android.play:app-update:2.0.1) and jetified-core-1.9.0-runtime (com.google.android.play:core:1.9.0)
     Duplicate class com.google.android.play.core.common.IntentSenderForResultStarter found in modules jetified-core-1.9.0-runtime (com.google.android.play:core:1.9.0) and jetified-core-common-2.0.2-runtime (com.google.android.play:core-common:2.0.2)
     Duplicate class com.google.android.play.core.common.LocalTestingException found in modules jetified-core-1.9.0-runtime (com.google.android.play:core:1.9.0) and jetified-core-common-2.0.2-runtime (com.google.android.play:core-common:2.0.2)
     Duplicate class com.google.android.play.core.common.PlayCoreDialogWrapperActivity found in modules jetified-core-1.9.0-runtime (com.google.android.play:core:1.9.0) and jetified-core-common-2.0.2-runtime (com.google.android.play:core-common:2.0.2)
     Duplicate class com.google.android.play.core.install.InstallException found in modules jetified-app-update-2.0.1-runtime (com.google.android.play:app-update:2.0.1) and jetified-core-1.9.0-runtime (com.google.android.play:core:1.9.0)
     Duplicate class com.google.android.play.core.install.InstallState found in modules jetified-app-update-2.0.1-runtime (com.google.android.play:app-update:2.0.1) and jetified-core-1.9.0-runtime (com.google.android.play:core:1.9.0)
     Duplicate class com.google.android.play.core.install.InstallStateUpdatedListener found in modules jetified-app-update-2.0.1-runtime (com.google.android.play:app-update:2.0.1) and jetified-core-1.9.0-runtime (com.google.android.play:core:1.9.0)
     Duplicate class com.google.android.play.core.install.NativeInstallStateUpdateListener found in modules jetified-app-update-2.0.1-runtime (com.google.android.play:app-update:2.0.1) and jetified-core-1.9.0-runtime (com.google.android.play:core:1.9.0)
     Duplicate class com.google.android.play.core.install.model.ActivityResult found in modules jetified-app-update-2.0.1-runtime (com.google.android.play:app-update:2.0.1) and jetified-core-1.9.0-runtime (com.google.android.play:core:1.9.0)
     Duplicate class com.google.android.play.core.install.model.AppUpdateType found in modules jetified-app-update-2.0.1-runtime (com.google.android.play:app-update:2.0.1) and jetified-core-1.9.0-runtime (com.google.android.play:core:1.9.0)
     Duplicate class com.google.android.play.core.install.model.InstallErrorCode found in modules jetified-app-update-2.0.1-runtime (com.google.android.play:app-update:2.0.1) and jetified-core-1.9.0-runtime (com.google.android.play:core:1.9.0)
     Duplicate class com.google.android.play.core.install.model.InstallStatus found in modules jetified-app-update-2.0.1-runtime (com.google.android.play:app-update:2.0.1) and jetified-core-1.9.0-runtime (com.google.android.play:core:1.9.0)
     Duplicate class com.google.android.play.core.install.model.UpdateAvailability found in modules jetified-app-update-2.0.1-runtime (com.google.android.play:app-update:2.0.1) and jetified-core-1.9.0-runtime (com.google.android.play:core:1.9.0)
     Duplicate class com.google.android.play.core.listener.StateUpdatedListener found in modules jetified-core-1.9.0-runtime (com.google.android.play:core:1.9.0) and jetified-core-common-2.0.2-runtime (com.google.android.play:core-common:2.0.2)
```

Let me know if I can provide any other information about the issue.

**Comment by SudoPlz** [comment]
Google is moving away from a single `com.google.android.play:core` package, and instead it’s splitting functionality into multiple packages.

https://developer.android.com/guide/playcore#playcore-migration 

The problem is that one of your dependencies is using the play:core (the old way of using google play library), and you have to migrate it to the new standards.

Our library has migrated, but you have to run `./gradlew :app:checkReleaseDuplicateClasses` on your android directory, and check which dependencies of yours are still using `com.google.android.play:core`, then patch them to make sure they're migrated to the new standards.

**Comment by diego-paired** [comment]
FYI if someone finds this in the future, the clash is with `react-native-in-app-review`

**Comment by SudoPlz** [comment]
Yeah, I had to do similar work on another repo [(react-native-store-review)](https://github.com/oblador/react-native-store-review/pull/78/files) to fix that.

It's not hard to do yourself, check it out.

**Comment by diego-paired** [comment]
thanks, I patch-packaged the dependency to remove play core and it worked fine.

**Comment by SudoPlz** [comment]
awesome, happy to hear that. Could you please share the patch here in case anyone else bumps into that issue? (and maybe also create a PR on that repo if you find time)

**Comment by alexander0205** [comment]
This work for me
[](https://stackoverflow.com/a/76043161/5963210)
